####################################################
#                                                  #
#                  |   MY_STYLE |                  #
#                                                  #
####################################################

#Contact with me:
#
#VK: vk.com/deelter
#DISCORD: DeelTer#4782
#TWITTER: twitter.com/roma200315
#YOUTUBE: www.youtube.com/channel/UCRACU2JfOfClrlEHImv5pYw

default-values:
  style: '&f%PLAYER%&f: %MESSAGE%'
  global-prefix: '&6G '
  local-prefix: '&aL '
  radius: 100
  mute: false
  notify: true

settings:
  chat:
    commands:
      private: true #Private commands: /msg /tell /ignore
      roleplay: true #Roleplay commands: /try /me, /do, /roll
    cooldown:
      enable: false
      seconds: 1
    replacer:
      enable: false
      words:
        - "пидарас=представитель ЛГБТ сообщества"
        - "шлюха=девушка лёгкого поведения"

  logs:
    console: true #Logs requests and other in console
    file: true #Logs requests in MyRequests/logs/ID.txt

messages:
  no-perm: '&8[&c#&8]&c У вас нету прав на использование'
  reload: '&8[&c#&8]&f Конфигурация перезагружена'
  chat:
    no-players: "&8[&c#&8]&c В вашем радиусе нет игроков"
    global-disable: "&8[&c#&8]&c У вас отключен глобальный чат"
    cooldown: "&8[&c#&8]&c Вы не можете писать в чат так часто!"
    ignore-you: "&8[&c#&8] &fДанный игрок игнорирует вас"
    player-ignore-add: "&8[&6#&8] &fТеперь вы игнорируете %PLAYER%"
    player-ignore-remove: "&8[&6#&8] &fВы больше не игнорируете %PLAYER%"

#Commands permissions
permissions:
  mute: 'chatsettings.mute' #Mute your global chat (/cs mute)
  notify: 'chatsettings.notify' #Off notifications about join/quit players (/cs notify)
  style: 'chatsettings.style' #Set your own style of chat (/cs style)
  prefix: 'chatsettings.prefix' #Set your own prefixes (/cs prefix)

##DEPRECATED: soon will remove this
#
#help:
#- '&a/cs style <style> &f- Изменить свой стиль чата. Переменные: (%PLAYER%; %MESSAGE%)'
#- '&a/cs prefix <local/global> <префикс> &f- Установить префикс глобального/локального чата!'
#- '&a/cs notify &f- Вкл/выкл уведомления о входе и выходе игроков'
#- '&a/cs mute &f- Вкл/выкл глобальный чат (работает только для игрока)'
